### PR TITLE
feat: Download videos and PDFs

### PR DESCRIPTION
**Pull request by quique**

### CODE REVIEW

**Comment by Fytch** [comment]
This fork doesn't work for me when trying to scrape e.g. [this lesson](https://www.japanesepod101.com/lesson/absolute-beginner-1-say-hello-in-japanese-no-matter-what-the-time-of-day/?lp=437). The error is:

```
Traceback (most recent call last):
  File "/tmp/tmp.RYXiqxPUy5/languagepod101-scraper/lesson1/../language101_scraper.py", line 277, in <module>
    main(args.username, args.password, args.url)
  File "/tmp/tmp.RYXiqxPUy5/languagepod101-scraper/lesson1/../language101_scraper.py", line 263, in main
    download_level(level_url)
  File "/tmp/tmp.RYXiqxPUy5/languagepod101-scraper/lesson1/../language101_scraper.py", line 233, in download_level
    pathways_urls = get_pathways_urls(level_url)
  File "/tmp/tmp.RYXiqxPUy5/languagepod101-scraper/lesson1/../language101_scraper.py", line 205, in get_pathways_urls
    pathways_links = level_soup.select(f'a[data-{level_name}="1"]')
  File "/usr/lib/python3.9/site-packages/bs4/element.py", line 1869, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/lib/python3.9/site-packages/soupsieve/__init__.py", line 98, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/lib/python3.9/site-packages/soupsieve/__init__.py", line 62, in compile
    return cp._cached_css_compile(pattern, namespaces, custom, flags)
  File "/usr/lib/python3.9/site-packages/soupsieve/css_parser.py", line 208, in _cached_css_compile
    CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
  File "/usr/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1043, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/lib/python3.9/site-packages/soupsieve/css_parser.py", line 894, in parse_selectors
    key, m = next(iselector)
  File "/usr/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1036, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Malformed attribute selector at position 1
  line 1:
a[data-?lp=437="1"]
 ^
```

**Comment by quique** [comment]
> This fork doesn't work for me when trying to scrape e.g. [this lesson](https://www.japanesepod101.com/lesson/absolute-beginner-1-say-hello-in-japanese-no-matter-what-the-time-of-day/?lp=437). 

In this fork you are not supposed to provide the link for a lesson, but for a language level.
I added code to detect this.

**Comment by Fytch** [comment]
Thank you, it works like a charm.

Another question: Is it possible to add a feature to resume scraping? I wanted to continue scraping a specific difficulty after aborting but the scraper greeted me with `FileExistsError: [Errno 17] File exists: 'bonus'`. It would be nice if I could just continue where it left off. The scraper possibly has to verify the progress within the individual lessons though.

**Comment by quique** [comment]
> Another question: Is it possible to add a feature to resume scraping? I wanted to continue scraping a specific difficulty after aborting but the scraper greeted me with `FileExistsError: [Errno 17] File exists: 'bonus'`.

Sure, pull and give it a try.

**Comment by nedlir** [comment]
This is a great initiative @quique!

However, it seems like the code is not able to connect to any of the sites.

**Comment by airmack** [comment]
My fork that is based on the code still works for me...

**Comment by Fytch** [comment]
I see the commit 'Revert "feat: Download videos and PDFs (#4)"' above; does that mean that @quique 's feature of also scraping the videos and PDFs wasn't merged to nedlir's master branch?

**Comment by airmack** [comment]
The source code in the master branch still contains all the relevant code. Not sure what happend

**Comment by iitjee** [comment]
I am unable to download any video.  It says "Lessons URLs successfully listed.
Yatta! Finished downloading the course~" but none were actually downloaded.

sampleURL:  https://www.chineseclass101.com/lesson-library/absolute-beginner-questions-answered-by-yinru/

**Pull request merged**
