### PR TITLE
2023 Update: Path URLs regex from class instead of options tag

### PR DESCRIPTION
**Pull request by alexander-y-lee**
## 1.) Update requirement dependency versions 

**For lxml library:**
image
```
      building 'lxml.etree' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
Failed to build lxml
ERROR: Could not build wheels for lxml, which is required to install pyproject.toml-based projects
```

**For requests library:**
image
`ModuleNotFoundError: No module named 'urllib3.packages.six.moves'`

image
```
\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
```

## 2.) Raw string invalid chars
image
`invalid escape sequence '\/'`

## 3.) New version checks for class containing a block of all the path urls and splits the paths using regex, instead of Options tag containing a list of values of path urls:

**New Version:**
image

https://www.chineseclass101.com/lesson/absolute-beginner-1-meeting-whats-your-name?lp=208
image

**Old Version:**

image

https://web.archive.org/web/20211129001640/https://www.chineseclass101.com/lesson/absolute-beginner-1-meeting-whats-your-name?lp=208
image

### CODE REVIEW

**Comment by alexander-y-lee** [comment]
Please review @nedlir @dp247 @airmack @quique

**Comment by alexander-y-lee** [comment]
[@Miguel](https://github.com/MiguellDomingues) Please review too

**Comment by dp247** [comment]
Haven't used in a while, but looks okay.

**Comment by AnasMAC** [comment]
Microsoft Windows [Version 10.0.19045.4651]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ert>"C:/Program Files/Python312/python.exe" c:/Users/ert/Downloads/languagepod101-scraper-2023update/languagepod101-scraper-2023update/language101_scraper.py
Traceback (most recent call last):
  File "c:\Users\ert\Downloads\languagepod101-scraper-2023update\languagepod101-scraper-2023update\language101_scraper.py", line 10, in <module>
    import requests
  File "C:\Users\ert\AppData\Roaming\Python\Python312\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Program Files\Python312\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Program Files\Python312\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Program Files\Python312\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
when open the language101_scraper that error appear what is the solution

**Comment by BenoitAnastay** [comment]
Outdated, check #28

**Pull request closed without merging**
